### ISSUE TITLE
invalid header field value when signing request

### ISSUE THREAD

**Issue by edovale** [cloudflare/origin-ca-issuer#105]
Hi,

We are using the origin issuer to renew certificates on our end. They recently expired and the origin issuer was unable to reissue a new cert with the following error: 

`{"level":"error","error":"unable to sign request: Post \"https://api.cloudflare.com/client/v4/certificates\": net/http: invalid header field value \"v1.0-[snip]\\n\" for key X-Auth-User-Service-Key","name":"origin-issuer/controllers/CertificateRequest","certificaterequest":{"Namespace":"prod","Name":"my-tls-tl6fr"},"time":"2024-01-14T18:02:25Z","message":"failed to sign certificate request"}`

I have reissued the API keys and updated all configuration associated to this and still getting the same problem. 

I had to lower the encryption mode to full from full (strict) in order to bring the site back up. Any help will be much appreciated.

**Comment by terinjokes** [comment]
It looks like your service key has an extra newline at the end of it.

**Comment by edovale** [comment]
Yeah. I thought of that but I have double check it many times and this is
not the case.

**Comment by Bakke** [comment]
We are having the same problem. It started this weekend, without any updates from our side. I double checked and recreated the “Origin CA Key” API key, but the origin issuer is still unable to reissue new certificates.

**Comment by terinjokes** [comment]
I'm taking a look, but nothing has changed on the controller side.

**Comment by terinjokes** [comment]
Just to confirm, you're seeing this issue with 0.6.1?

**Comment by tnimni** [comment]
Anyone managed to solve this?

**Comment by Bakke** [comment]
> Just to confirm, you're seeing this issue with 0.6.1?

I updated to `0.6.1`, but the issue persists. I did not update `origin-ca-issuer` before the problem first occurred, so it might seem like an update to the Cloudflare API has broken the integration.

**Comment by edovale** [comment]
I am 0.6.1 =>

*Image*:          cloudflare/origin-ca-issuer:v0.6.1

**Comment by edovale** [comment]
> > Just to confirm, you're seeing this issue with 0.6.1?
> 
> I updated to `0.6.1`, but the issue persists. I did not update `origin-ca-issuer` before the problem first occurred, so it might seem like an update to the Cloudflare API has broken the integration.

I was thinking the same thing. On my side nothing upgraded and the issue showed up. In my case this could be the first time certs needed to be renewed so there is a chance this code is executing for the first time in my environment. It did generate a new certificate when I first moved our stuff over to cloudflare.

I can consistently reproduce the problem. Is there a way I can activate logs to help with this?

**Comment by terinjokes** [comment]
@Bakke version 0.6.1 is running in my cluster without issue. After updating the Origin CA API token, can you restart the origin-ca-issuer pods and then use the cert-manager CLI to start a [renewal manually](https://cert-manager.io/docs/reference/cmctl/#renew)?

**Comment by terinjokes** [comment]
@edovale Can you clarify which error message you're seeing?

**Comment by edovale** [comment]
`
{
  "level": "error",
  "error": "unable to sign request: Post \"https://api.cloudflare.com/client/v4/certificates\": net/http: invalid header field value \"v1.0-2fc643d7353b45e562d928c6-59f690f6a2a1ec26c0856afba44cd4b72987df31adf87f8e04f ... b24aea1\\n\" for key X-Auth-User-Service-Key",
  "name": "origin-issuer/controllers/CertificateRequest",
  "certificaterequest": {
    "Namespace": "prod",
    "Name": "my-tls-tl6fr"
  },
  "time": "2024-01-14T18:02:25Z",
  "message": "failed to sign certificate request"
}
`

**Comment by terinjokes** [comment]
How did you create the secret with the Origin CA API key? It has a newline at the end. After it's removed, if you can follow the same steps as in https://github.com/cloudflare/origin-ca-issuer/issues/105#issuecomment-1892299373 that would be great.

**Comment by edovale** [comment]
This is the yaml for the secret. It puzzles me to see that \n char at the
end of the value but it is not there in the actual secret as far as I can
tell.

**Comment by terinjokes** [comment]
Please don't paste your secrets here, even if you attempt to obscure them.

Note that the secret representation in Kubernetes YAML and JSON form is base64 encoded. You can check with something similar to: `kubectl get secret service-key -oyaml | jq '.data.key | @base64d'` (don't paste the output of this here!) Do you see `\n` in the output?

**Comment by edovale** [comment]
My apologies. It seems something changed in my shell environment that the output of base64 was garbled. 
I have resolved the problem now. It had a \n at the end. I have created the secret a different way now and it all works fine. 
Weird how it worked before though. Maybe a kubernetes update or something?

**Comment by terinjokes** [comment]
I'm going to close this issue. If you have an error related to invalid header values, please check your secret doesn't have newlines. If you're having issues with Authentication Errors code 10000 from the API, please see #108.
