### ISSUE TITLE
Docker image  cloudflare/origin-ca-issuer:v0.7.0 not found

### ISSUE THREAD

**Issue by dasunNimantha** [cloudflare/origin-ca-issuer#106]
With the latest changes it tries to download the docker image version 0.7.0  which is not available

**Comment by terinjokes** [comment]
It hasn't been released yet, due to some permission issues with the service account and Docker Hub.

**Comment by terinjokes** [comment]
The service account has been fixed, and the Action rerun. This is now published, and GitHub Release created. :partying_face:

**Comment by dasunNimantha** [comment]
Thanks for the update
