### ISSUE TITLE
x509: certificate signed

### ISSUE THREAD

**Issue by shinofara** [cloudflare/origin-ca-issuer#11]
```
$ kubectl logs origin-ca-issuer-55484d5db6-xmcnn -n origin-ca-issuer

{"level":"error","error":"unable to sign request: Post \"https://api.cloudflare.com/client/v4/certificates\": x509: certificate signed by unknown authority","name":"controller","reconcilerGroup":"cert-manager.io","reconcilerKind":"CertificateRequest","controller":"certificaterequest","name":"mfkasia-tls-hr67n","namespace":"hoge","time":"2020-12-18T03:03:38Z","message":"Reconciler error"}
```

Is this a CA certificate old problem?

**Comment by terinjokes** [comment]
I'm not sure. As I explained before, I'm still working on doing testing for this for an release.

**Comment by shinofara** [comment]
I will try to partially solve the Image Build

**Comment by terinjokes** [comment]
It's fine. I'm already working on the fix.

**Comment by shinofara** [comment]
@terinjokes 
Thank you for solving the problem.
https://github.com/cloudflare/origin-ca-issuer/pull/12

I would be grateful if you could create a `tag: 0.5.1` tag.
I want to use new image
