### ISSUE TITLE
[ERROR] K8S + cloudflare origin-ca-issuer

### ISSUE THREAD

**Issue by vovkanaz** [cloudflare/origin-ca-issuer#114]
Hi there, we've faced an Error during the CertificateRequest process:
```
Failed to sign certificate request: unable to sign request: Cloudflare API Error code=1100 message=Failed to write certificate to Database
```
Unfortunately, the CloudFlare API article doesn't explain the root cause of this issue.
Maybe the team could shed insight on how to fix this. I appreciate any help you can provide.

**Comment by terinjokes** [comment]
These are temporary errors related to storing signed certificates in the API. They should succeed on retry.

**Comment by vovkanaz** [comment]
@terinjokes Thanks a lot for the quick response, maybe it is possible to add forced retry in configs in case of an error?
