### ISSUE TITLE
Random certificate missbehavior.

### ISSUE THREAD

**Issue by yma-het** [cloudflare/origin-ca-issuer#116]
Certs are correctly being issued until i've got the following error:

> The certificate request has failed to complete and will be retried: Failed to sign certificate request: unable to sign request: Cloudflare API Error code=1201 message=CA signing failure. Could not parse returned certificate

To fix this, i must delete all of originIssuer objects and recreate them. Any suggestions what is wrong?

**Comment by terinjokes** [comment]
As I mentioned in https://github.com/cloudflare/origin-ca-issuer/issues/115#issuecomment-1952183514 the expectation is cert-manager would retry a certificate renewal at a later time, so deleting OriginIssuers should be unnecessary.

As for the actual error, nope. Sounds like the API service this project calls is having issues.

**Comment by yma-het** [comment]
> As I mentioned in [#115 (comment)](https://github.com/cloudflare/origin-ca-issuer/issues/115#issuecomment-1952183514) the expectation is cert-manager would retry a certificate renewal at a later time, so deleting OriginIssuers should be unnecessary.

Certificate was stuck in this state for 2 days. After recreation of OriginIssuer and editing ingress so it does not have tls section and reverting those changes back, it fixed the problem immediately.

It is the third time i have such situation, so it does not looks like single bit upset case.

**Comment by vovkanaz** [comment]
@yma-het Yes, we are also still facing such behavior, it seems like it doesn't work properly
`    message: >-
        The certificate request has failed to complete and will be retried:
        Failed to sign certificate request: unable to sign request: Cloudflare
        API Error code=1100 message=Failed to write certificate to Database
      observedGeneration: 1
      reason: Failed
      status: 'False'
      type: Issuing`

<img width="259" alt="image" src="https://github.com/cloudflare/origin-ca-issuer/assets/6215653/bfd7e784-0285-4539-a8a0-70019b1bba8c">

It was working well after recreating the certificate manually.
<img width="259" alt="image" src="https://github.com/cloudflare/origin-ca-issuer/assets/6215653/2722bad9-e2dd-40c0-b600-9a368bcab5b7">

**Comment by terinjokes** [comment]
Okay. I'm not sure why cert-manager doesn't create a new CertificateRequest, but I'll change how the issuer handles these errors.

**Comment by vovkanaz** [comment]
@terinjokes Thanks a lot, we could provide more error traces, if needed, to be able to figure it out ASAP

**Comment by Timeraa** [comment]
I also have this issue randomly on either of our 3 clusters but there are from what I was looking at no helpful errors / errors at all, the certificate then expires but doesn't renew apparently at all... It works fine on my private project but at work I only seem to be getting issues with it.

From what I looked at, cert manager, the origin issuer etc. I could not find any useful logs if any to begin with

**Comment by ksh-chy** [comment]
I have also been facing issue fairly often as of recently - in a few of our clusters. First it just happened once, but over the last few weeks, we've hit this bug a couple times on different certs. 

The logs aren't super useful. Our mitigation by deleting the `CertficateRequest` and forcing a renewal works well enough, but it is becoming tedious over time.

**Comment by shanehughes1990** [comment]
Same is happening to us periodically with the same 1201 error. I just delete the certificate itself and a new one takes its place but it does mean that SSL breaks until a human gets to it. (I really don't want to write a checker of sorts to do that.)

**Comment by terinjokes** [comment]
I finally have a little bit of time to work on addressing this issue and I should have a PR this week.

**Comment by shanehughes1990** [comment]
If you need beta debuggers let me know 👍

**Comment by mikocot** [comment]
> I finally have a little bit of time to work on addressing this issue and I should have a PR this week.

how is that going?

**Comment by terinjokes** [comment]
I was working on a change to migrate to [the official Go SDK](https://github.com/cloudflare/cloudflare-go/tree/v2), to avoid needing to implement this change twice, but I ran into some showstopper bugs there. So I guess I'm going to need to implement it twice. :/
