### ISSUE TITLE
feature: Add support to use bearer token for API authentication

### ISSUE THREAD

**Issue by tcinbis** [cloudflare/origin-ca-issuer#135]
Hey everyone!

We would like to make use of the origin-ca-issuer in our Kubernetes clusters, but noticed that the code is currently hard-coded to use the [`X-Auth-User-Service-Key`](https://github.com/cloudflare/origin-ca-issuer/blob/7b16c1daa5d0dcd0c376eaefa47ce430f14be455/internal/cfapi/cfapi.go#L104) for authentication.

It would be nice if we can make this authentication header configurable to allow us to e.g. use a bearer token instead. We tested it on our end by replacing above line with this.

```go
r.Header.Add("Authorization", fmt.Sprintf("Bearer %s", string(c.serviceKey)))
```

The use case for us is that we can not use the Origin CA API key (as suggested in #108) since we are a larger enterprise. And handing out tokens with account level permissions is not an option. Therefore, we are only allowed to use API tokens that are have permissions limited to individual zones.

If you can provide us some pointers as to where the right place for such config would be (via CLI flags maybe?) and if it is a welcome contribution, I will open a PR with that change.

Thanks!
Tom

**Comment by terinjokes** [comment]
This API endpoint [is documented](https://developers.cloudflare.com/api/operations/origin-ca-list-certificates) as only supporting Origin CA API keys. I'm not aware of any changes to that support since #108.

**Comment by tcinbis** [comment]
Hey @terinjokes,

thanks for the quick reply! I just tested the API endpoint both in Postman and with the forked origin-ca-issuer and can confirn that the Bearer token is supported. And it has been for at least a year now.

**Comment by terinjokes** [comment]
Works is different than supported. I'll ask the team to confirm support by updating the documentation.

**Comment by tcinbis** [comment]
Thanks! Maybe just missing from the docs. If it helps, we also have a CF internal case regarding this: #01046080

**Comment by tunix** [comment]
Hi @terinjokes , since you included this issue into the milestone, does that mean you received a positive response from the team? Do you have a guesstimate date for the release?

**Comment by terinjokes** [comment]
I did not. I was just organizing this ticket, and some other large tickets, for my own workflow.

**Comment by xaoo** [comment]
> Works is different than supported. I'll ask the team to confirm support by updating the documentation.

I am not sure what you mean by not supported, here: https://developers.cloudflare.com/fundamentals/api/get-started/keys/
Its clearly stated that API Keys are legacy.

Imagine companies having 1 API Key per the entire organization, we cannot just give that key to our every tenant, therefore we use, as specified in the above documentation the API Tokens per tenant.

**Comment by terinjokes** [comment]
That page is for global API keys. The [Origin CA Key](https://developers.cloudflare.com/fundamentals/api/get-started/ca-keys/) is entirely separate, and not marked as legacy.

**Comment by terinjokes** [comment]
I've heard back from the team, and they're in the process of updating the developer docs (https://github.com/cloudflare/cloudflare-docs/pull/17162) and the API docs. I'll be able to work on adding the support to this controller shortly.
