### ISSUE TITLE
Create a tag for latest changes in the trunk branch

### ISSUE THREAD

**Issue by imatviian** [cloudflare/origin-ca-issuer#137]
Could you please tag the latest changes in the trunk branch with the new patch version v0.9.1? The latest commit includes important fixes to the Helm chart, but there is no tag for these changes. I would like to use the chart from the upstream, tied to a specific version.

Thank you.

**Comment by sahaqaa** [comment]
:+1:

**Comment by dgamanenko** [comment]
👍

**Comment by olehs0** [comment]
👍

**Comment by vnastenko** [comment]
Absolutely! Tagging the latest changes in the trunk branch with the new patch version v0.9.1 would be really helpful. 

Thank you for considering this!

**Comment by terinjokes** [comment]
The helm chart is released independently of the service and the fix was included in version 0.5.7 of the helm chart.
