### ISSUE TITLE
I would be grateful if you could create a tag: 0.5.1 tag.

### ISSUE THREAD

**Issue by shinofara** [cloudflare/origin-ca-issuer#14]
Thank you for solving the problem.
https://github.com/cloudflare/origin-ca-issuer/pull/12

I would be grateful if you could create a tag: 0.5.1 tag.
I want to use new image

**Comment by terinjokes** [comment]
Should be doing this today.

**Comment by sashahilton00** [comment]
Would be great if you could, currently can't use this in our cluster due to the CA store not being present.
