### ISSUE TITLE
publish helm charts

### ISSUE THREAD

**Issue by Nicklason** [cloudflare/origin-ca-issuer#17]
I am trying to set up Origin CA Issuer automatically using Terraform. The problem I have is that you need to clone the repository to install it.

It would be very simple to do if the yaml files in each step were combined into a single file. That way you can apply it using the raw github url, like with the CRDs: `kubectl apply -f https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml`

It would also be nice if something like https://github.com/helm/chart-releaser-action was used to publish the helm chart.

**Comment by terinjokes** [comment]
Aside from the CRDs, the manifests are minimal, and there's an expectation that you'll need or want to customize them for a production environment. I'll continue to revisit this as I work towards 1.0.

As for Helm charts, I've been chatting with others in the community of the best way to have those packaged up.

**Comment by Nicklason** [comment]
Thank you for the quick response! I will just copy the files and wait for the helm chart to be published.

**Comment by xunholy** [comment]
Moving my original comment to this thread

> It would be great to host the helm charts and have them published.
This is primarily useful for automation tools where users may use helm repositories to integrate with tools such as Flux(v1/v2) and ArgoCD. It also allows for ease of semantic versioning of your chart releases and easy rollbacks during remediation for users when newer releases introduce breaking changes and is a little cleaner than depending on a git source and using a release/branch.

**Comment by marjorg** [comment]
@terinjokes Any updates on this?

**Comment by xunholy** [comment]
@terinjokes this has been a long time since this has been addressed - This doesn't cause a lot of confidence in the project, even if you commit the index.yaml we could use this helm chart remotely.

eg: ```helm repo add origin-ca-issuer https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/charts/```

However, without even the index.yaml being commit we're stuck with cloning and rendering these manifests which is a large PITA.

**Comment by terinjokes** [comment]
@xUnholy I don't use Helm, so I'm not entirely sure what is missing. This is also an open source project of one person (me), getting this done is part of being happy with a 1.0 release.

**Comment by LeoColomb** [comment]
@terinjokes In order to use Helm, a `index.yaml` listing versions and their assets is required. See official documentation here: https://helm.sh/docs/topics/chart_repository/#create-a-chart-repository

In the ideal world, this file is hosted somewhere behind something like a website. As part of GitHub Actions/Helm workflows everything is automatic, it only requires a `gh-pages` branch. That is the goal of my pull request #29.

In the minimal world, @xUnholy's suggestion makes the trick (i.e. manually creating and maintaining an `index.yml` inside the repo). Easier to configure initially but harder to maintain in a long term.

**Comment by terinjokes** [comment]
I was hoping the Chart.yaml would be enough for folks to get started. Of course the tools would require more unnecessary complexity.

I'll reluctantly go set this up.

**Comment by LeoColomb** [comment]
While I understand your reply, the unnecessary complexity here is honestly quite necessary to actually use the chart with Helm correctly and definitely not that complex.
Again, my PR introduces the usage of the official [helm releaser tool](https://github.com/helm/chart-releaser) which does everything for you (publishes the releases, creates the assets, updates the index.yaml).

**Comment by terinjokes** [comment]
No no, I'm not saying you're making it complex, or even that the index.xml is complex. I'm just thinking they made the common use case (use a chart from a GitHub release) involve more steps than necessary.

**Comment by LeoColomb** [comment]
Ah ok 🙂 True. I think this is the main cost of decentralizing services, Helm being not relative to any "official" package provider/server.

**Comment by xunholy** [comment]
@terinjokes is there anything further we can do to help this progress? I do see the PR that will hopefully address this already but if there is anything else please reach out 🙏

**Comment by terinjokes** [comment]
We've experimentally published charts at `https://cloudflare.github.io/origin-ca-issuer/charts`. If this works for you (modulo #45) I can add information to the readme for v0.7.0.

**Comment by bkshrader** [comment]
> We've experimentally published charts at `https://cloudflare.github.io/origin-ca-issuer/charts`. If this works for you (modulo #45) I can add information to the readme for v0.7.0.

Can we expect this release any time soon, and is this documentation currently available anywhere?

**Comment by claywd** [comment]
tested the helm chart and it works. Will update readme
