### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by rubenv** [cloudflare/origin-ca-issuer#2]
Any plans to provide a Helm chart?

This would greatly simplify automated deployment.

**Comment by terinjokes** [comment]
I'm not too familiar with Helm v2 charts or their best practices, but it's something I can look into as part of preparing for a release here.

**Comment by rubenv** [comment]
Well as of today Helm v2 isn't supported anymore so I'd skip that and go straight to 3 :-)

**Comment by terinjokes** [comment]
The v2 _charts_ are supported by Helm 3. Helm 2 used _v1 charts_.

Yes, this scheme is confusing.

**Comment by rubenv** [comment]
My bad, apologies!

**Comment by terinjokes** [comment]
No worries. I'll stick to talking about "Helm 3" from now on to avoid confusion.

**Comment by xunholy** [comment]
+1 helm support, please.

**Comment by matthewdaltonditto** [comment]
Any update on this looking to get this rolled out in a gitops configuration would like a solidified helm chart to work off of

**Comment by terinjokes** [comment]
I'm still waiting to resolve #1 before I think about tagging a release.
