### ISSUE TITLE
Publish Helm Chart with Github Pages

### ISSUE THREAD

**Issue by xunholy** [cloudflare/origin-ca-issuer#21]
It would be great to host the helm charts and have them published.

This is primarily useful for automation tools where users may use helm repositories to integrate with tools such as Flux(v1/v2) and ArgoCD. It also allows for ease of semantic versioning of your chart releases and easy rollbacks during remediation for users when newer releases introduce breaking changes and is a little cleaner than depending on a git source and using a release/branch.

**Comment by terinjokes** [comment]
Duplicates #17.
