### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by bejaneps** [cloudflare/origin-ca-issuer#27]
Hi, guys, first of all thanks for creating this extension for cert-manager.

I'm having an issue with certificate verification after successful installation of origin-ca-issuer by Cloudflare. So, I configured origin-ca-issuer to work with cert-manager and it issues Cloudflare certificates without any problem, but when I send requests to server either with curl or other software, certificate can't get verified for some reason. The only workaround I found so far, was to include Cloudflare's Origin CA root certificate in each request.

Error from curl:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

When I bypass verification using **-k** flag on curl, certificate issuer is correct:
```
issuer: C=US; O=CloudFlare, Inc.; OU=CloudFlare Origin SSL Certificate Authority; L=San Francisco; ST=California
```

Can you suggest something or how to deal with this issue ?

**Comment by terinjokes** [comment]
This issuer creates certificates that work with Cloudflare's Origin CA, allowing you to use the stricter SSL verification modes on sites using the Cloudflare service. These certificates aren't trusted by operating systems or distributions.

The error you're seeing with curl is the symptom of this issue. curl is unable to find a CA in the trust store for the certificate being presented.

If you want to use this issuer, you need to send requests though Cloudflare.

**Comment by bejaneps** [comment]
@terinjokes thanks for rapid reply. So, if I understood you correct,I have to either send all client requests through Cloudflare or I can use a Certificate Authority like Let's Encrypt for the server, so curl or other software can verify the certificates. Is it right ?

**Comment by terinjokes** [comment]
Yes. You'll need to send all requests through Cloudflare.

If you chose Let's Encrypt, you'll also need to configure cert-manager so that it can complete ACME challenges, and the certificates will be issued for a shorter amount of time (though cert-manager will try to renew before expiration).

**Comment by bejaneps** [comment]
@terinjokes okay, got you, thanks for help !
