### ISSUE TITLE
Unable to issue certificates for ingress

### ISSUE THREAD

**Issue by mashbrno** [cloudflare/origin-ca-issuer#35]
There are two issues:
1. I've followed the readme, but it's unable to find *prod-issuer*. I've tried to place it in *default* namespace as well as in *origin-ca-issuer* with no success.
2. The ingress is requesting secretName `tls-admintool`, but there are attempts to generate `tls-admintool-bqrd6` with some random suffix. Such secrets won't match and ingress will not work.

```
origin-ca-controller
{"level":"error","error":"OriginIssuer.cert-manager.k8s.cloudflare.com \"prod-issuer\" not found","name":"controller","reconcilerGroup":"cert-manager.io","reconcilerKind":"CertificateRequest","controller":"certificaterequest","name":"tls-admintool-bqrd6","namespace":"data3s-cz-test","time":"2021-05-25T19:30:25Z","message":"Reconciler error"}
```

**Comment by terinjokes** [comment]
> I've followed the readme, but it's unable to find `prod-issuer`.

This needs to be in the same namespace as where your making the Certificate (or using ingress annotations)

> Such secrets won't match and ingress will not work.

Those are `certificaterequests`, not secrets. This project only works with `certificaterequests`, it's cert-manager that turns completed requests into secrets.

**Comment by mashbrno** [comment]
My bad. I haven't read the yaml for single certificate. #36 
Now works as expected. Thank you!
