### ISSUE TITLE
Nginx controller warns about expiring certificate

### ISSUE THREAD

**Issue by mashbrno** [cloudflare/origin-ca-issuer#38]
Is there any option to prolong certificate validity or set the validity threshold on nginx ingress controller? Currently it warns every 3 minutes:
```
SSL certificate for server "example.com" is about to expire (2021-06-02 07:45:00 +0000 UTC)
```
per nginx pod per issued certificate.

**Comment by terinjokes** [comment]
- You can prolong the certificate validity by setting `duration` on the Certificate object (or Ingress annotation `cert-manager.io/duration` if you're using cert-manager's Ingress support).
- You can adjust when certificates are renewed by adjusting `renewBefore` (or `cert-manager.io/renew-before`).
- If you don't like the log messages, you can file an issue with ingress-nginx, I have nothing to do with it.
