### ISSUE TITLE
API Token instead of CA key

### ISSUE THREAD

**Issue by tkbits9** [cloudflare/origin-ca-issuer#40]
Hi there. 

As I understand the API Token isn't supported at the mom and the recommended usage is origin ca keys. However, I'd like to know if there's any workaround in case I cannot use the ca key due to the company's policy? 

Many thanks, 
T.

**Comment by terinjokes** [comment]
Nope, at this time only the Origin CA API Key is supported by the API endpoints.

**Comment by tkbits9** [comment]
Thanks @terinjokes! Any ideas when this feature would be available or planned for the roadmap?

**Comment by terinjokes** [comment]
There's been no change in the API support here, nor has Cloudflare stated anything about when or if this will be supported. Since there's nothing I can do here, closing out this ticket. Fill free to reopen when and if this support is added to the Cloudflare API.

X-Ref: ACCT-1871
