### ISSUE TITLE
Revoke old Origin Certificates

### ISSUE THREAD

**Issue by SerhatTeker** [cloudflare/origin-ca-issuer#51]
Hi,

Is there a way/an opt to revoke expired certificates via origin-ca-issuer?
As an example I have an `Ingress Certificate` which is responsible for my origin certificates; 

<details>
<summary>Certificates Screenshot</summary>

![Screenshot from 2021-12-23 14-01-16](https://user-images.githubusercontent.com/45147900/147232769-6011412a-c622-4ae9-a191-691efd623ff3.png)
</details>

**Comment by terinjokes** [comment]
That's not a feature of origin-ca-issuer or cert-manager. The lifecycle of a certificate is managed by cert-manager, which notifies origin-ca-issue when it's time to issue new certificates. I would have to add extra logic to keep track of previously issued certificates, potentially across restarts, and know when the certificate has been removed from the cluster and it's safe to revoke. That's a lot of surface area with potential for errors.

It may be better to provide product feedback within the Cloudflare dash to hide away expired origin certificates.

**Comment by SerhatTeker** [comment]
Yes, as far as I recall cert-manager doesn't provide this feature. Adding extra logic/debt, as you mentioned doesn't worth probably. I can `list` and `revoke` them via CF API. Cleaner way I guess.

As a customer I don't mind certificates on dash, just wondered whether possible or not. Thank you for your info.
