### ISSUE TITLE
Doesn't check for existing certificates

### ISSUE THREAD

**Issue by joaogl** [cloudflare/origin-ca-issuer#55]
Hello,

I've been using for 2 weeks or so this origin-ca-issuer for staging purposes where we have automatic deployments being done.
Today I had to create an origin certificate manually and when I checked, we actually had over 8000 certificates, and about 5000 or so of those were all actually from a single subdomain.
I'm not sure what the hell happened, still trying to debug the situation but one thing seems to be wierd, shouldn't origin-ca-issuer before issueing a new certificate check if there isn't one already for that exact same subdomain? and if so re-use it?

Thanks,
João Lourenço

**Comment by terinjokes** [comment]
origin-ca-issuer responds to lifecycle events from cert-manager, which triggers them when needed, which already takes into account validity of the certificate in the cluster.

Once the lifecycle event from cert-manager happens, it's either to make a new cert or renew an existing one: and both are the same action in the Cloudflare API.

I'm not sure there's a situation where it makes sense to check for an existing certificate.

**Comment by joaogl** [comment]
but, even if a request to generate a new certificate comes to origin-ca-issuer, should it check on cloudflare api if the certificate is already there?
I still couldn't find out how it is that the cluster requested for 5 thousand certs but truth is it did... and all for the same cert. 🤔

**Comment by terinjokes** [comment]
Certificates are tied to private keys, which origin-ca-issuer never sees, since we see CSRs. There would be no way to reuse an existing certificate, because the private key would be wrong.
