### ISSUE TITLE
secret for certificate has only tls.key and with Full (strict) mode I see 526 error

### ISSUE THREAD

**Issue by PDVJAM** [cloudflare/origin-ca-issuer#57]
Hey. Was using LE for my Origin certs, decided to move to CF's certificates. Installed everything as in manual, using ingresses annotations to create SSL cert, but instead, the full cert secret has only tls.key and in the Strict mode CF shows me 526 error. Cert issuer and ingress are in the same namespace, issuer tells me it is ready (as in the manual). What might be wrong?
Origin CA key is correct, secret is in place.

**Comment by terinjokes** [comment]
You should check the status of the `Certificate` and any created `CertificateRequest`s to see if any error are logged. A fully issued certificate will have both a `tls.key` and a `tls.cert`.

**Comment by PDVJAM** [comment]
> You should check the status of the `Certificate` and any created `CertificateRequest`s to see if any error are logged. A fully issued certificate will have both a `tls.key` and a `tls.cert`.

In Certificate I see:
```
Status:
  Conditions:
    Last Transition Time:        2022-04-18T04:58:49Z
    Message:                     Issuing certificate as Secret does not exist
    Reason:                      DoesNotExist
    Status:                      True
    Type:                        Issuing
    Last Transition Time:        2022-04-18T04:58:50Z
    Message:                     Issuing certificate as Secret does not exist
    Reason:                      DoesNotExist
    Status:                      False
    Type:                        Ready
  Next Private Key Secret Name:  bab.gg-n9k5g
Events:
  Type    Reason     Age    From          Message
  ----    ------     ----   ----          -------
  Normal  Issuing    5m55s  cert-manager  Issuing certificate as Secret does not exist
  Normal  Generated  5m55s  cert-manager  Stored new private key in temporary Secret resource "bab.gg-n9k5g"
  Normal  Requested  5m55s  cert-manager  Created new CertificateRequest resource "bab.gg-74h6b"
```

In CertificateRequests I see
```
  Request:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2ZqQ0NBV1lDQVFBd0FEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5mQgpjTlZCT0RVWlIwRC9ZcW1mTXZTRWRranE2bXJsRVJVZ29pZnJQeldQM3NlbHdLcmpkMS94OVFZRzB4TGQ3T2hOClo0cWJDN3IwMzVza0RUaHhBaG1HYzgycEFaYWliKzdvRTEwYzlZY0hCUzQ4aDFTQkNWaEplRmJmVERmc1Z5ek8KUGNiNDZTd0VTQkhWRzA4SGNRVTd0ZnYwQmxidXJtV3NSOVF6Nm12UGVIdHpBdVUydnBqd2hjOEpVMW1jQU5jawp6bmlxQUZ6S1ZnMUI4RTVOdXExSkJiaWoyVExGZXRTQk1ieXZtWm1HcGpXWnEydWhMMG1US1JmWG5idFROYmE2ClRVM3RraGlSzlhZlM1NSt2TWJrcnpwVHZ1ZmdZT1djUGZoN2hTN3RzaWJnaDl2U3hOTjBTbVY3UlR0eENGL2wKdm9yWE96ZEl0RkF5cTNQZG5Wc0NBd0VBQWFBNU1EY0dDU3FHU0liM0RRRUpEakVxTUNnd0dRWURWUjBSQkJJdwpFSUlPWkdWMkxtSmhZbTl2Ym5NdVoyY3dDd1lEVlIwUEJBUURBZ1dnTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQzY4alh4K1RhRUxPZUY1NVpOSkFkSzJxL3dld2Juc0pVSkF1QTVMdWdnN1V4SzYwang3endzNSsxdHVRcnUKVDFwd0ZBU3paZ29lVkJKRlZCUnFmS1FhSFFUWlZoTXg0dGpBRmZJUTJ2SktXanpXdXgxd0tIN1hsZ3dFOVZVZwpUNERhSEx2N0R3N2lOZFp4Qml5VzFuYi92Q1pVRXpHZkxkQy9vS0JzZjVFVkNoeDV5SHROTkYxbUdJejJ0dS83CnNTV21reGFhNGxzd0xJVW1DS09vV3YxY290SitraG8ra2Q1bE0rOHRIdUh1Q0tRYXZ1R1JwQ3B0VGZsb04rUnIKSWxnR2dNTHYrTXZsMlRxWEZhS2daaGhzVjZid0dIc2J3dyt5T09SSHByYU9SK2k0WjlPYm1LRnVKWGg4OU5RaQpWVGVGMXVXZTNKV3FzZFFXSElERFRwd0UKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
Events:     <none>
```

And in logs of origin-ca-issuer
```
{"level":"debug","verbosity":4,"name":"origin-issuer/controllers/CertificateRequest","certificaterequest":{"Namespace":"test","Name":"bab.gg-74h6b"},"time":"2022-04-18T04:58:50Z","message":"certificate request has not been approved"}
```

I don't see any Orders to be created as well.
Any ideas?..

**Comment by terinjokes** [comment]
Okay, so origin-ca-issuer is waiting for cert-manager to register that the Certificate request has been approved. Normally this is approved automatically with a [Cluster Role Binding](https://github.com/cloudflare/origin-ca-issuer/blob/trunk/deploy/rbac/role.yaml#L67) that we include in this repo. However, in some setups, they may need to be [approved via other means](https://cert-manager.io/docs/concepts/certificaterequest/#approval).

What versions of cert-manager and origin-ca-issuer are you using? And how have you deployed them?

**Comment by PDVJAM** [comment]
> Okay, so origin-ca-issuer is waiting for cert-manager to register that the Certificate request has been approved. Normally this is approved automatically with a [Cluster Role Binding](https://github.com/cloudflare/origin-ca-issuer/blob/trunk/deploy/rbac/role.yaml#L67) that we include in this repo. However, in some setups, they may need to be [approved via other means](https://cert-manager.io/docs/concepts/certificaterequest/#approval).
> 
> What versions of cert-manager and origin-ca-issuer are you using? And how have you deployed them?

origin-ca-issuer is the latest from this repo, deployed with manifests.
cert-manager deployed via helm, version 1.2.0.

**Comment by terinjokes** [comment]
Approval support was added on cert-manager v1.3.0. I recommend upgrading it, but I'd you can't you can disable origin-ca-issuer's check for approval by setting [controller.disableApprovedCheck](https://github.com/cloudflare/origin-ca-issuer/tree/trunk/deploy/charts/origin-ca-issuer#configuration) in your Helm configuration.
