### ISSUE TITLE
Helm repo not available

### ISSUE THREAD

**Issue by secorona** [cloudflare/origin-ca-issuer#67]
Hi folks, we are trying to use terraform to install the origin-ca-issuer into a kubernetes cluster but we were not able to identify the remote repo to pass to the next command:

- helm repo add origin-ca-issuer <remote-repo>

Do you happen to know if it is possible to install it with the command above or we have to download the repo and then run helm install?

Thank you in advance

**Comment by terinjokes** [comment]
Currently you need to clone the repository and run `helm install`, after installing the necessary CRDs.
