### ISSUE TITLE
OriginRSA and OriginECC are flipped?

### ISSUE THREAD

**Issue by ckwalsh** [cloudflare/origin-ca-issuer#72]
Take a look at https://github.com/cloudflare/origin-ca-issuer/blob/39d567ab36e06e8613e034e104386e703759a671/pkgs/provisioners/origin.go#L108-L111

I just installed origin-ca-issuer (it works great!), but I noticed I got a `SHA256-RSA` signature when using the `OriginIssuer` example from the `README`, which sets `requestType: OriginECC`.

Conversely, when I updated it to `requestType: OriginRSA` and forced a certificate to be reissued, I got a `ECDSA-SHA256` signature.

**Comment by terinjokes** [comment]
Well, that's ackward. This area was refectored as part of open sourcing, so I'll have to check pre-history to understand what went wrong. I suspect a bad merge somehow happened.
