### ISSUE TITLE
Multi-cluster kubernetes deployment

### ISSUE THREAD

**Issue by christosnc** [cloudflare/origin-ca-issuer#73]
Hello,

I have a multi-cluster infrastructure, with cert-manager on **each cluster**. I would like to produce a certificate for the same domain on all clusters.

So basically when time comes for the renewal, all clusters will make a request for the same domain.

I would like to know if this is possible. For example this is not possible with let's encrypt issuer since it rate limits duplicate requests for the same domain to 5, so when time comes to renew, if you have more than 5 clusters, you will be rate limited as each cluster will make a separate request.

I just wanted to know if there is a similar rate limit.

Thanks a lot.

**Comment by terinjokes** [comment]
My understanding is Origin Certificates are subjected to the same API rate limit as the rest of the Cloudflare V4 API, which is documented as:

> The Cloudflare API sets a maximum of 1,200 requests in a five minute period.

I don't see any rate limit more specific documented, but I can ask the team.

As Origin CA is only trusted in connections between the origin host and Cloudflare, and not publicly, I think there's significantly less overhead than what Let's Encrypt has.

**Comment by christosnc** [comment]
Thanks for the quick response!

Yes, that's what I was thinking as well, but I couldn't just assume because the impact would be huge!

Please ask if you can and just confirm if indeed that's the case.

**Comment by terinjokes** [comment]
The rate limits described in the API reference seem to be accurate.
