### ISSUE TITLE
API Token instead of CA key

### ISSUE THREAD

**Issue by alberk8** [cloudflare/origin-ca-issuer#85]
I know this has been asked and answer before.  Is there still plans to support the use of API Token instead of CA Key.   Thank you.

**Comment by terinjokes** [comment]
No plans to support it until there is support for it in the Cloudflare API.

**Comment by trajan0x** [comment]
Is this being tracked anywhere? Would love to subscribe to an issue to get notified when this is fixed

**Comment by terinjokes** [comment]
Im not aware of a public place to track this, nor do I know when or if the team reponsible will implement this.
