### ISSUE TITLE
CertificateRequest is not getting approved

### ISSUE THREAD

**Issue by bramhoven** [cloudflare/origin-ca-issuer#86]
I have tried installing it through the deployment manifests through `kubectl apply` and also through the helm chart, but I cannot seem to get the CertificateRequest approved. 
I tried deleting and reapplying the certificate to get it to approve but it is not working. I got all the RBAC manifests applied as well.

Any ideas I could try to get it working?

**Comment by terinjokes** [comment]
This repository doesn't ship anything that would approve CertificateRequests, as that requires knowledge of your environment along with your organization's access and change control policies.

However, cert-manager's default configuration configures an approver that automatically approves all requests. Have you changed this configuration, and have you consulted the cert-manager logs?

**Comment by bramhoven** [comment]
@terinjokes I thought the ClusterRole and the ClusterRoleBinding shipped in this repo made sure that the CertificateRequests would get approved. I did not check the cert-manager logs. I saw that I used the bitnami cert-manager helm chart, so I am now trying the jetstack one. Maybe that will already fix it. Otherwise I'll check the cert-manager logs

**Comment by terinjokes** [comment]
The ClusterRole and ClusterRoleBinding allow cert-manager to approve the requests. If you deployed cert-manager with a different service account name or into another namespace, you may be running into #83.

Edit: merged a fix for the Helm chart.

**Comment by bramhoven** [comment]
@terinjokes it does now work after moving to the `jetstack/cert-manager` instead of the `bitnami/cert-manager`... Completely my fault 🤦🏻  Thanks for your quick response!
