### ISSUE TITLE
Install CRDs with Helm chart

### ISSUE THREAD

**Issue by bkshrader** [cloudflare/origin-ca-issuer#89]
Installing CRDs as a separate step before running helm makes it more difficult to manage infrastructure using Terraform, particularly since the CRDs are [currently incompatible with the Terraform Kubernetes Provider](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1428). I propose adding them to the helm chart in the same way that cert-manager has: using set installCRDs=true when running helm.

**Comment by terinjokes** [comment]
As explained elsewhere, this is not something we're planning on doing.
