### ISSUE TITLE
Feature: Edge cert creation parrallel to origin cert creation.

### ISSUE THREAD

**Issue by deuxailes** [cloudflare/origin-ca-issuer#91]
Pretty much the title. From what I can understand this only creates origin certs. Is it possible to create edge certs for each origin cert created?

**Comment by terinjokes** [comment]
I think that's outside the scope of a cert-manager issuer. cert-manager really expects to be handed the private key material, which isn't available from edge certificates.

If you need to order edge certificates outside the ones setup by default, I would look at using our Terraform provider for that, and continue to use this issuer for the CF to host certificate.
